version: '3.5'

services:
  stream_search_service:
    container_name: stream_search
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/data'
      # own build dir inside the container
      - '/data/build'
      - '/data/data'
  frontend:
    container_name: stream_search_frontend
    build:
      context: ./
      dockerfile: DockerfileFrontend
    ports: 
      - "3000:3000"
    volumes:
      - './:/data'
      - '/data/frontend/node_modules'
