version: '3.5'

services:
  stream_search_service:
    container_name: stream_search
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/data'
      # own build dir inside the container
      - '/data/build'
